### ISSUE TITLE
Upgrade to Scading 0.13.1 and Scala 2.11.6

### ISSUE THREAD

**Issue by stephanh** [CommBank/uniform#46]
Next sprint (27/4) we are planning on upgrading to Scading 0.13.1 and Scala 2.11.6.

* The new version of scalding is has a number of bug fixes and improvements
* Scala 2.11 has improvements for Macros amongst other things.

The impact this will have as of yet is unknown. However, macro code might be heavily affected.

@anandsiva @dg2 @jamindaw @quintona please make the teams in your portfolios aware of this.

Status:
- [x] uniform
- [x] omnia-test
- [x] omnitool
- [x] permafrost
- [x] humbug
- [x] cascading-hive
- [x] thermometer
- [x] parlour
- [x] ebenezer
- [x] edge
- [x] answer
- [x] maestro

**Comment by stephanh** [comment]
Ran into a problem with the lack of scrooge-bijection for Scala 2.11. I have raised an issue against bijection to figure out where it is since there are other Scala 2.11 bijection projects.

**Comment by SamRoberts** [comment]
Unless we use scrooge-bijection a lot in some code I haven't seen, it could be replaced with a handful of 3-4 line utility methods.

**Comment by stephanh** [comment]
Added status update to issue description.

I am currently stuck on Thermometer, something really weird is happening where the tests seem to run but no test information is displayed and the tests are marked as failure without any information.

@anandsiva at this stage I don't think we will be ready for any loads to be tested this sprint.

**Comment by stephanh** [comment]
Currently struggling with the different source generators from scrooge, humbug and thrift interacting weirdly as part of the upgrade in enbenezer.

**Comment by stephanh** [comment]
Now stuck untangeling Parlour. What ever was done with regards to how parlour does configuration does not work for Scala 2.11.

**Comment by stephanh** [comment]
Ebenezer is now done as well. It was going slow because we had to run the tests differently and travis kept running out of memory.

**Comment by stephanh** [comment]
There is a 2.11 branch of Maestro that is being tested right now.

**Comment by stephanh** [comment]
All done.
