### ISSUE TITLE
Investigate shapeless version we should use

### ISSUE THREAD

**Issue by stephanh** [CommBank/uniform#49]
@lancelet @mjhopkins as part of the Scala, Scalding update can you please determine which version of Shapeless we should adopt. I think the latest version of specs2 currently uses shapeless 2.1

**Comment by lancelet** [comment]
@stephanh @mjhopkins
I can confirm that the latest version of specs2 (both 3.3.1 and the `master` branch on GitHub) use shapeless 2.1. shapeless 2.2 has not yet been released, but a release is expected soon. So, without further information, shapeless 2.1 seems to be the best candidate.

An important question: how should we proceed to test an upgrade to specs2, shapeless, and the other interdependent projects (eg scalacheck)? Is the following sufficient?
  1. build a `publishLocal` version of uniform with the new changes,
  2. build `publishLocal` versions of the Maestro dependencies with bumped uniform versions (thermometer, ebenezer, omnitool, permafrost, edge, humbug, parlour - did I miss any?)
  3. build maestro

Or is there a better way to go about things? @stephanh, what would you recommend?

**Comment by SamRoberts** [comment]
For investigating strict conflict issues, I would recommend creating a new dummy project that has no code to speak of, but pulls in everything from uniform-dependency, plus maybe sqoop and selected other jars as well.

**Comment by stephanh** [comment]
@lancelet in order to actually test that there are no problems right now you would have to build the whole stack (using publish local) until you get to your project. I am currently looking into dbuild http://typesafehub.github.io/dbuild/0.9.2/index.html to get it to propagate the changed projects for testing. However, I'm not sure how it will do when you have to fix compile errors somewhere in the middle.

@SamRoberts I'm setting up a test for uniform that does that.

**Comment by stephanh** [comment]
Uniform now has a dependency test.
