### ISSUE TITLE
Adding `hadoop-client` to non-uniform

### ISSUE THREAD

**Issue by shyam334** [CommBank/uniform#59]
Background : 
`Ebenezer` depends on the external dependency `parquet-tools`, 
Which despite being used with `noHadoop`, Would still require an exclude for `hadoop-client`.
`parquet-tools` will pull `hadoop-client-2.5.0-cdh5.2.4` (The `hadoop()` method in uniform would pull `hadoop-client-2.5.0-mr1-cdh5.2.4`)

From what I can see, We would need to add `hadoop-client-2.5.0-cdh5.2.4` to exclude list (Until `yarn`). 
Since it's not a part of the `hadoop classpath`, I presume it's an exclude only item. 
I'm not sure if I should modify the current `noHadoop` or add a new method. 

What are your thoughts.

**Comment by SamRoberts** [comment]
In the uniform dependency class, there is the following snippet of code:
```
    // These jars have classes which interfere with the classes provided by hadoop
    // so we exclude these as well
    val interferingModules = List[ModuleID](
      "org.apache.hadoop" % "hadoop-mapreduce-client-core"   % depend.versions.hadoopNoMr1,
      "org.apache.hadoop" % "hadoop-mapreduce-client-common" % depend.versions.hadoopNoMr1
    )
```

It sounds to me that the hadoop client would go in this list. Does that sound right?

**Comment by shyam334** [comment]
Yes, It does. I'll raise a PR.
Thanks.
